### ISSUE TITLE
Understanding the "score" system

### ISSUE THREAD

**Issue by Pandaism** [uhcs2320/hwFive#5]
I dont understand what (how) we are suppose to use the "score" system to sort. I imagine that we would have to calculate the score for each person then sort using the score. However, the instruction feels like it's telling us to calculate the score while sorting, find the top candidates then increments at the end, then calculate the score again and sort then repeat until x > 20.

**Comment by aleman** [comment]
Calculate score for each person.
Sort using the score.
Select individuals based on score. (six total in the example).
This completes the one iteration.

increment x, do another iteration. 

increment x, do another iteration. And so on and so forth until x > 20.

Every iteration needs to calculate scores, and needs to sort.
