### ISSUE TITLE
Correctness of outputs for test cases.

### ISSUE THREAD

**Issue by vlykarye** [uhcs2320/hwFive#7]
Hey guys,
If anyone gets different outputs for the test cases than the ones in "testcases/hw5/test-1", please let me know on here, through email, or discord. I checked through the outputs to make sure the results look reasonable, but I can't promise that they are correct (cus bugs).
Thanks!

- eric

**Comment by Akshay199456** [comment]
Hey Eric,

I ran through the test cases and am getting the same results.

Best
Akshay

**Comment by vlykarye** [comment]
That is good to hear. I have 2 confirms and 1 rejects so far.
The outputs were created using std::sort, so there can be no issue with sorting.
The score calculations are easy enough.

**Comment by rafaelarmando** [comment]
Got the same results as well.

Thanks,

Rafael
